services:
  # PostgreSQL Database (Using Remote Server)
  # Note: Database is hosted remotely at 157.10.73.52
  # No local postgres container needed

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: mentoring-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mentoring-network

  # Backend API (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mentoring-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=157.10.73.52
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=P@ssw0rd
      - DB_NAME=plp_mentoring_sovath
      - DB_SSL=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-cambodia-mentoring-2024
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - mentoring-network
    command: npm run start:dev

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mentoring-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - mentoring-network
    command: sh -c "npm install && npm run dev"

volumes:
  redis_data:

networks:
  mentoring-network:
    driver: bridge