version: '3.8'

services:
  # Redis for caching and sessions
  redis:
    image: docker.io/redis:7-alpine
    container_name: mentoring-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mentoring-network

  # Backend API (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: mentoring-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=157.10.73.52
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=P@ssw0rd
      - DB_NAME=plp_mentoring_sovath
      - DB_SSL=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-cambodia-mentoring-2024
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./backend:/app:z
      - backend_node_modules:/app/node_modules
    depends_on:
      - redis
    networks:
      - mentoring-network
    command: node simple-server.js

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mentoring-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    volumes:
      - ./frontend:/app:z
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - mentoring-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  redis_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  mentoring-network:
    driver: bridge