version: '3.8'

services:
  # Mock Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.mock
    container_name: mentoring-backend-mock
    ports:
      - "3000:3000"
    networks:
      - mentoring-network

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mentoring-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    volumes:
      - ./frontend:/app:z
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - mentoring-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  frontend_node_modules:

networks:
  mentoring-network:
    driver: bridge