version: '3.8'

services:
  # Mock Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.mock
    container_name: mentoring-backend-mock
    ports:
      - "3000:3000"
    restart: always  # Auto-restart on failure or system reboot
    networks:
      - mentoring-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/v1/auth/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev-fix
    container_name: mentoring-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    volumes:
      - ./frontend:/app:z
      - frontend_node_modules:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: always  # Auto-restart on failure or system reboot
    networks:
      - mentoring-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  frontend_node_modules:
    driver: local

networks:
  mentoring-network:
    driver: bridge
    name: mentoring-network